# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Common configuration for local as well as remote environment
common: &common
  asset_host: <%= ENV["RAILS_ASSET_HOST"] %>

# Configuration specific to local environment
local: &local
  <<: *common
  perform_caching: true # switch to false caching should be disabled in development environment
  
# Configuration specific to remote environment such as test/staging/production 
remote: &remote
  <<: *common
  dynamodb_access_key_id: 'AKIAJA2CCM2SXX4VAFCA'
  dynamodb_secret_access_key: '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'
  dynamodb_region: 'us-east-2'

development:
  secret_key_base: 672632293f877aa75ba496d9acce50268fd6114ceaf41465cfb1f17401984d12e667e450081c803ebc91b2c5aefd34c23ba79a0bb56425f71220867d1423fc2b

test:
  secret_key_base: 612f09d6279b763cd22fefc0f0ba22c504da21b9eb106a1c0e1fc55c2be40094164f2ada46e404e02e151dc260bc43f533c6e25013e31ef207d3254a6a62cc09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ddcc0bb183271cd7f54c886e6d56f6eae9e6174751ed28a8cfae3366922c244f917f37315d1435fa2d3df82a88310d46e895a4c21ec8eb8dab72937483940021
